// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HcsYNjKi4HZnOSKNsF50mr-QE83UR8M',
    appId: '1:255870965956:web:768b665de0709c03e0d191',
    messagingSenderId: '255870965956',
    projectId: 'mad3-firebaseauth',
    authDomain: 'mad3-firebaseauth.firebaseapp.com',
    storageBucket: 'mad3-firebaseauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80aaO29n-b3KfuXQ5qILn_g0r0CETa-Y',
    appId: '1:255870965956:android:591f2f739d7aa959e0d191',
    messagingSenderId: '255870965956',
    projectId: 'mad3-firebaseauth',
    storageBucket: 'mad3-firebaseauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lDo2jtt6Ur2W-rnJRwDGV4MpANKMj9A',
    appId: '1:255870965956:ios:e606bbf257642fbde0d191',
    messagingSenderId: '255870965956',
    projectId: 'mad3-firebaseauth',
    storageBucket: 'mad3-firebaseauth.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
